#!/bin/sh


set -e


case $1 in
        configure)
             #Senia repositories
	    echo " * Senia Cron : Setting a Basic Shutdown"
	    senia-cron shutdown_23 || true
            ;;

        abort-upgrade|abort-remove|abort-deconfigure)
                echo "postinst called with argument \`$1'" >&2
                exit 1
        ;;

        *)
                echo "postinst called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac
#DEBHELPER#

exit 0
