#!/usr/bin/python3


import os
import sys
from xml.etree import ElementTree

fileDb="/home/tic/Descargas/imexalum.xml"
listaProfes=[]

class Profesor:

    nombre = ""
    apellido1 = ""
    apellido2 = ""
    dni =""

    def __init__(self,dni="",nombre="",apellido1="",apellido2=""):
        self.nombre = nombre
        self.apellido1 = apellido1
        self.apellido2 = apellido2
        self.dni = dni

def sanity_checks():
    if (os.path.exists(fileDb)):
        print(" * File Exists!")
    else:
        print(" * Dame un ficherin ")
        sys.exit(1)


def read_ocupaciones(f):
    with open(f,'rt') as f:
        tree = ElementTree.parse(f)

    for ocupacion in tree.iter('ocupacion'):
        print(ocupacion.attrib)

def read_all(f):
    with open(f,'rt') as f:
        tree = ElementTree.parse(f)

    for prof in tree.iter('docente'):
        #print(prof.attrib)
        aux_profe = Profesor(prof.attrib['documento'],prof.attrib['nombre'],prof.attrib['apellido1'],prof.attrib['apellido2'])
        listaProfes.append(aux_profe)
    
    '''
    for profesor in listaProfes:
        print(profesor.dni)
    '''

    for dia in ["L","M","X","J","V"]:

        for node in tree.iter('horario_ocupacion'):

            if (dia == node.attrib['dia_semana']):
        
            
                if ( node.attrib['ocupacion']== "821898618" or node.attrib['ocupacion']== "3249454" ):
                    docenteid = node.attrib['docente']
                    docenteAux = Profesor()
                
                    for aux in listaProfes:
                        if ( aux.dni == docenteid):
                            docenteAux.dni = aux.dni
                            docenteAux.nombre= aux.nombre
                            docenteAux.apellido1 = aux.apellido1
                            docenteAux.apellido2 = aux.apellido2

                   
                    print(" * -  " + node.attrib['dia_semana'] + " - " + node.attrib['sesion_orden'] + " ... " +docenteAux.nombre + " Guardia" )
                
                #print(node.attrib)
    

if __name__ == "__main__":

    sanity_checks()
    read_all(fileDb)
    #read_ocupaciones(fileDb)
    sys.exit(0)
